import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <div className="flex justify-center items-center w-screen h-[100px]">
          <div className="flex w-[90%] justify-between">
            <a href="/"><div className="flex justify-start text-[20px] font-bold">J. C.</div></a>
            <div className="flex">
              <a href="/about"><div className="flex ml-[40px] justify-end text-[20px] font-bold">About</div></a>
              <a href="/projects"><div className="flex ml-[40px] justify-end text-[20px] font-bold">Projects</div></a>
              <a href="/contact"><div className="flex ml-[40px] justify-end text-[20px] font-bold">Contact</div></a>
            </div>
          </div>
        </div>

        {children}

        <div className="flex justify-center items-center w-screen h-[50px]">
          <div className="flex w-[90%] justify-between text-[12px] font-bold">
            <div>DESIGN BY JOCHUAN.</div>
            <div>2025</div>
          </div>
        </div>

      </body>
    </html>
  );
}
