// 專案清單 儲存預覽圖版型、個別頁面都會使用到的基本資訊

export const projects = [
    {
        label: "frontend_portfolioweb",
        href: "/projects/frontend_portfolioweb",
        title: "Jo-Chuan's Portfolio",
        category: "作品集網站",
        year: "2026",
        photo: "/images/frontend_portfolioweb/portfolioweb-01.png",
        tools: ["Next.js", "Tailwind CSS", "React Bits", "Figma"],
        filter: "Frontend",
        explore: ["frontend_report", "uiux_chance"],
    },
    {
        label: "thesis_vrvolleyball",
        href: "/projects/thesis_vrvolleyball",
        title: "虛擬實境對現場觀賽意圖之影響研究",
        category: "碩士論文",
        year: "2025",
        photo: "/images/thesis_vrvolleyball/thesis-01.png",
        tools: ["Meta Quest 3", "Insta360 X5", "Insta360 Studio", "SPSS"],
        filter: "Thesis",
        explore: ["thesis_newsgame", "uiux_chance"],
    },
    {
        label: "uiux_chance",
        href: "/projects/uiux_chance",
        title: "Chance!!",
        category: "產品架構與專案規劃",
        year: "2025",
        photo: "/images/uiux_chance/chance-01.png",
        tools: ["Figma", "Flowchart", "Wireframing", "Prototyping", "Notion"],
        filter: "UI/UX",
        explore: ["uiux_aha", "thesis_vrvolleyball"],
        selected: true
    },
    {
        label: "game_spike",
        href: "/projects/game_spike",
        title: "SPIKE IT UP!!",
        category: "2D 網頁遊戲",
        year: "2025",
        photo: "/images/game_spike/spike-01.png",
        tools: ["HTML", "TailwindCSS", "Next.js", "React Hooks"],
        filter: "Games",
        explore: ["game_cross", "frontend_period"]
    },
    {
        label: "thesis_newsgame",
        href: "/projects/thesis_newsgame",
        title: "化身相似性對新聞遊戲效果之影響研究",
        category: "研究小論文",
        year: "2024",
        photo: "/images/thesis_newsgame/newsgame-01.png",
        tools: ["Gather Town", "JASP", "SEM"],
        filter: "Thesis",
        explore: ["thesis_vrvolleyball", "frontend_report"],
    },
    {
        label: "uiux_aha",
        href: "/projects/uiux_aha",
        title: "A HA~",
        category: "使用者研究與功能優化",
        year: "2024",
        photo: "/images/uiux_aha/aha-01.png",
        tools: ["Figma", "Flowchart", "Wireframing", "Prototyping"],
        filter: "UI/UX",
        explore: ["uiux_chance", "frontend_report"],
        selected: true
    },
    {
        label: "frontend_period",
        href: "/projects/frontend_period",
        title: "月來悅貼心",
        category: "Chatbot 與地圖整合網頁",
        year: "2024",
        photo: "/images/frontend_period/period-01.png",
        tools: ["HTML", "CSS", "JavaScript", "Empathy Map", "Persona", "User Journey Map"],
        filter: "Frontend",
        explore: ["frontend_report", "frontend_portfolioweb"]
    },
    {
        label: "frontend_report",
        href: "/projects/frontend_report",
        title: "薪租翹翹板",
        category: "數據新聞專題網站",
        year: "2023",
        photo: "/images/frontend_report/report-01.png",
        tools: ["Web Scraper", "Flourish", "HTML", "CSS", "Empathy Map", "Persona", "User Journey Map"],
        filter: "Frontend",
        explore: ["uiux_chance", "mg_typhoon"],
        selected: true
    },
    {
        label: "game_mirror",
        href: "/projects/game_mirror",
        title: "鏡像之境",
        category: "互動體驗",
        year: "2023",
        photo: "/images/game_mirror/mirror.png",
        tools: ["Unity", "Blender"],
        filter: "Games",
        explore: ["game_cross", "game_spike"]
    },
    {
        label: "game_cross",
        href: "/projects/game_cross",
        title: "麥側過馬路",
        category: "3D 遊戲",
        year: "2023",
        photo: "/images/game_cross/cross-01.png",
        tools: ["Unity"],
        filter: "Games",
        explore: ["game_spike", "mg_nccu3m"]
    },
    {
        label: "mg_nccu3m",
        href: "/projects/mg_nccu3m",
        title: "NCCU in Under 3 Minutes",
        category: "資訊動畫",
        year: "2023",
        photo: "/images/mg_nccu3m/nccu3m-01.png",
        tools: ["After Effects"],
        filter: "Motion Graphics",
        explore: ["mg_tennis", "mg_boat"]
    },
    {
        label: "mg_tennis",
        href: "/projects/mg_tennis",
        title: "球后的崛起",
        category: "資訊動畫",
        year: "2022",
        photo: "/images/mg_tennis/tennis-05.png",
        tools: ["Illustrator", "After Effects", "Audition"],
        filter: "Motion Graphics",
        explore: ["mg_boat", "mg_typhoon"]
    },
    {
        label: "mg_boat",
        href: "/projects/mg_boat",
        title: "〈船〉歌詞 MV",
        category: "動畫",
        year: "2022",
        photo: "/images/mg_boat/boat-01.png",
        tools: ["Illustrator", "After Effects"],
        filter: "Motion Graphics",
        explore: ["mg_tennis", "design_fruit"]
    },
    {
        label: "design_fruit",
        href: "/projects/design_fruit",
        title: "水果指南",
        category: "Logo 設計",
        year: "2022",
        photo: "/images/design_fruit/fruit-03.png",
        tools: ["Illustrator"],
        filter: "Visual Design",
        explore: ["design_vnccu", "mg_tennis"]
    },
    {
        label: "mg_typhoon",
        href: "/projects/mg_typhoon",
        title: "颱風假到底怎麼放？",
        category: "資訊圖表、動畫",
        year: "2022",
        photo: "/images/mg_typhoon/typhoon-01.png",
        tools: ["PowerPoint", "Excel"],
        filter: "Motion Graphics",
        explore: ["mg_nccu3m", "frontend_report"]
    },
    {
        label: "design_vnccu",
        href: "/projects/design_vnccu",
        title: "政大之聲開播週",
        category: "主視覺設計",
        year: "2021",
        photo: "/images/design_vnccu/vnccu-01.jpg",
        tools: ["Illustrator"],
        filter: "Visual Design",
        explore: ["design_fruit", "mg_boat"]
    },

];